# Generated by Django 4.1.5 on 2023-02-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/shop/images')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/shop/images'),
        ),
    ]
